# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/FC8006E78006A7EA/Users/tarek/Desktop/College/Year3/Second Term/CG/project/GameX"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/FC8006E78006A7EA/Users/tarek/Desktop/College/Year3/Second Term/CG/project/GameX"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/FC8006E78006A7EA/Users/tarek/Desktop/College/Year3/Second Term/CG/project/GameX/CMakeFiles" "/mnt/FC8006E78006A7EA/Users/tarek/Desktop/College/Year3/Second Term/CG/project/GameX/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/FC8006E78006A7EA/Users/tarek/Desktop/College/Year3/Second Term/CG/project/GameX/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GAME_APPLICATION

# Build rule for target.
GAME_APPLICATION: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GAME_APPLICATION
.PHONY : GAME_APPLICATION

# fast build rule for target.
GAME_APPLICATION/fast:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/build
.PHONY : GAME_APPLICATION/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f vendor/glfw/src/CMakeFiles/glfw.dir/build.make vendor/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

source/common/application.o: source/common/application.cpp.o

.PHONY : source/common/application.o

# target to build an object file
source/common/application.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/application.cpp.o
.PHONY : source/common/application.cpp.o

source/common/application.i: source/common/application.cpp.i

.PHONY : source/common/application.i

# target to preprocess a source file
source/common/application.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/application.cpp.i
.PHONY : source/common/application.cpp.i

source/common/application.s: source/common/application.cpp.s

.PHONY : source/common/application.s

# target to generate assembly for a file
source/common/application.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/application.cpp.s
.PHONY : source/common/application.cpp.s

source/common/asset-loader.o: source/common/asset-loader.cpp.o

.PHONY : source/common/asset-loader.o

# target to build an object file
source/common/asset-loader.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/asset-loader.cpp.o
.PHONY : source/common/asset-loader.cpp.o

source/common/asset-loader.i: source/common/asset-loader.cpp.i

.PHONY : source/common/asset-loader.i

# target to preprocess a source file
source/common/asset-loader.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/asset-loader.cpp.i
.PHONY : source/common/asset-loader.cpp.i

source/common/asset-loader.s: source/common/asset-loader.cpp.s

.PHONY : source/common/asset-loader.s

# target to generate assembly for a file
source/common/asset-loader.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/asset-loader.cpp.s
.PHONY : source/common/asset-loader.cpp.s

source/common/components/camera.o: source/common/components/camera.cpp.o

.PHONY : source/common/components/camera.o

# target to build an object file
source/common/components/camera.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/components/camera.cpp.o
.PHONY : source/common/components/camera.cpp.o

source/common/components/camera.i: source/common/components/camera.cpp.i

.PHONY : source/common/components/camera.i

# target to preprocess a source file
source/common/components/camera.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/components/camera.cpp.i
.PHONY : source/common/components/camera.cpp.i

source/common/components/camera.s: source/common/components/camera.cpp.s

.PHONY : source/common/components/camera.s

# target to generate assembly for a file
source/common/components/camera.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/components/camera.cpp.s
.PHONY : source/common/components/camera.cpp.s

source/common/components/free-camera-controller.o: source/common/components/free-camera-controller.cpp.o

.PHONY : source/common/components/free-camera-controller.o

# target to build an object file
source/common/components/free-camera-controller.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/components/free-camera-controller.cpp.o
.PHONY : source/common/components/free-camera-controller.cpp.o

source/common/components/free-camera-controller.i: source/common/components/free-camera-controller.cpp.i

.PHONY : source/common/components/free-camera-controller.i

# target to preprocess a source file
source/common/components/free-camera-controller.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/components/free-camera-controller.cpp.i
.PHONY : source/common/components/free-camera-controller.cpp.i

source/common/components/free-camera-controller.s: source/common/components/free-camera-controller.cpp.s

.PHONY : source/common/components/free-camera-controller.s

# target to generate assembly for a file
source/common/components/free-camera-controller.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/components/free-camera-controller.cpp.s
.PHONY : source/common/components/free-camera-controller.cpp.s

source/common/components/mesh-renderer.o: source/common/components/mesh-renderer.cpp.o

.PHONY : source/common/components/mesh-renderer.o

# target to build an object file
source/common/components/mesh-renderer.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/components/mesh-renderer.cpp.o
.PHONY : source/common/components/mesh-renderer.cpp.o

source/common/components/mesh-renderer.i: source/common/components/mesh-renderer.cpp.i

.PHONY : source/common/components/mesh-renderer.i

# target to preprocess a source file
source/common/components/mesh-renderer.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/components/mesh-renderer.cpp.i
.PHONY : source/common/components/mesh-renderer.cpp.i

source/common/components/mesh-renderer.s: source/common/components/mesh-renderer.cpp.s

.PHONY : source/common/components/mesh-renderer.s

# target to generate assembly for a file
source/common/components/mesh-renderer.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/components/mesh-renderer.cpp.s
.PHONY : source/common/components/mesh-renderer.cpp.s

source/common/components/movement.o: source/common/components/movement.cpp.o

.PHONY : source/common/components/movement.o

# target to build an object file
source/common/components/movement.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/components/movement.cpp.o
.PHONY : source/common/components/movement.cpp.o

source/common/components/movement.i: source/common/components/movement.cpp.i

.PHONY : source/common/components/movement.i

# target to preprocess a source file
source/common/components/movement.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/components/movement.cpp.i
.PHONY : source/common/components/movement.cpp.i

source/common/components/movement.s: source/common/components/movement.cpp.s

.PHONY : source/common/components/movement.s

# target to generate assembly for a file
source/common/components/movement.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/components/movement.cpp.s
.PHONY : source/common/components/movement.cpp.s

source/common/ecs/entity.o: source/common/ecs/entity.cpp.o

.PHONY : source/common/ecs/entity.o

# target to build an object file
source/common/ecs/entity.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/ecs/entity.cpp.o
.PHONY : source/common/ecs/entity.cpp.o

source/common/ecs/entity.i: source/common/ecs/entity.cpp.i

.PHONY : source/common/ecs/entity.i

# target to preprocess a source file
source/common/ecs/entity.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/ecs/entity.cpp.i
.PHONY : source/common/ecs/entity.cpp.i

source/common/ecs/entity.s: source/common/ecs/entity.cpp.s

.PHONY : source/common/ecs/entity.s

# target to generate assembly for a file
source/common/ecs/entity.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/ecs/entity.cpp.s
.PHONY : source/common/ecs/entity.cpp.s

source/common/ecs/transform.o: source/common/ecs/transform.cpp.o

.PHONY : source/common/ecs/transform.o

# target to build an object file
source/common/ecs/transform.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/ecs/transform.cpp.o
.PHONY : source/common/ecs/transform.cpp.o

source/common/ecs/transform.i: source/common/ecs/transform.cpp.i

.PHONY : source/common/ecs/transform.i

# target to preprocess a source file
source/common/ecs/transform.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/ecs/transform.cpp.i
.PHONY : source/common/ecs/transform.cpp.i

source/common/ecs/transform.s: source/common/ecs/transform.cpp.s

.PHONY : source/common/ecs/transform.s

# target to generate assembly for a file
source/common/ecs/transform.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/ecs/transform.cpp.s
.PHONY : source/common/ecs/transform.cpp.s

source/common/ecs/world.o: source/common/ecs/world.cpp.o

.PHONY : source/common/ecs/world.o

# target to build an object file
source/common/ecs/world.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/ecs/world.cpp.o
.PHONY : source/common/ecs/world.cpp.o

source/common/ecs/world.i: source/common/ecs/world.cpp.i

.PHONY : source/common/ecs/world.i

# target to preprocess a source file
source/common/ecs/world.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/ecs/world.cpp.i
.PHONY : source/common/ecs/world.cpp.i

source/common/ecs/world.s: source/common/ecs/world.cpp.s

.PHONY : source/common/ecs/world.s

# target to generate assembly for a file
source/common/ecs/world.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/ecs/world.cpp.s
.PHONY : source/common/ecs/world.cpp.s

source/common/material/material.o: source/common/material/material.cpp.o

.PHONY : source/common/material/material.o

# target to build an object file
source/common/material/material.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/material/material.cpp.o
.PHONY : source/common/material/material.cpp.o

source/common/material/material.i: source/common/material/material.cpp.i

.PHONY : source/common/material/material.i

# target to preprocess a source file
source/common/material/material.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/material/material.cpp.i
.PHONY : source/common/material/material.cpp.i

source/common/material/material.s: source/common/material/material.cpp.s

.PHONY : source/common/material/material.s

# target to generate assembly for a file
source/common/material/material.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/material/material.cpp.s
.PHONY : source/common/material/material.cpp.s

source/common/material/pipeline-state.o: source/common/material/pipeline-state.cpp.o

.PHONY : source/common/material/pipeline-state.o

# target to build an object file
source/common/material/pipeline-state.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/material/pipeline-state.cpp.o
.PHONY : source/common/material/pipeline-state.cpp.o

source/common/material/pipeline-state.i: source/common/material/pipeline-state.cpp.i

.PHONY : source/common/material/pipeline-state.i

# target to preprocess a source file
source/common/material/pipeline-state.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/material/pipeline-state.cpp.i
.PHONY : source/common/material/pipeline-state.cpp.i

source/common/material/pipeline-state.s: source/common/material/pipeline-state.cpp.s

.PHONY : source/common/material/pipeline-state.s

# target to generate assembly for a file
source/common/material/pipeline-state.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/material/pipeline-state.cpp.s
.PHONY : source/common/material/pipeline-state.cpp.s

source/common/mesh/mesh-utils.o: source/common/mesh/mesh-utils.cpp.o

.PHONY : source/common/mesh/mesh-utils.o

# target to build an object file
source/common/mesh/mesh-utils.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/mesh/mesh-utils.cpp.o
.PHONY : source/common/mesh/mesh-utils.cpp.o

source/common/mesh/mesh-utils.i: source/common/mesh/mesh-utils.cpp.i

.PHONY : source/common/mesh/mesh-utils.i

# target to preprocess a source file
source/common/mesh/mesh-utils.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/mesh/mesh-utils.cpp.i
.PHONY : source/common/mesh/mesh-utils.cpp.i

source/common/mesh/mesh-utils.s: source/common/mesh/mesh-utils.cpp.s

.PHONY : source/common/mesh/mesh-utils.s

# target to generate assembly for a file
source/common/mesh/mesh-utils.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/mesh/mesh-utils.cpp.s
.PHONY : source/common/mesh/mesh-utils.cpp.s

source/common/shader/shader.o: source/common/shader/shader.cpp.o

.PHONY : source/common/shader/shader.o

# target to build an object file
source/common/shader/shader.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/shader/shader.cpp.o
.PHONY : source/common/shader/shader.cpp.o

source/common/shader/shader.i: source/common/shader/shader.cpp.i

.PHONY : source/common/shader/shader.i

# target to preprocess a source file
source/common/shader/shader.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/shader/shader.cpp.i
.PHONY : source/common/shader/shader.cpp.i

source/common/shader/shader.s: source/common/shader/shader.cpp.s

.PHONY : source/common/shader/shader.s

# target to generate assembly for a file
source/common/shader/shader.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/shader/shader.cpp.s
.PHONY : source/common/shader/shader.cpp.s

source/common/systems/forward-renderer.o: source/common/systems/forward-renderer.cpp.o

.PHONY : source/common/systems/forward-renderer.o

# target to build an object file
source/common/systems/forward-renderer.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/systems/forward-renderer.cpp.o
.PHONY : source/common/systems/forward-renderer.cpp.o

source/common/systems/forward-renderer.i: source/common/systems/forward-renderer.cpp.i

.PHONY : source/common/systems/forward-renderer.i

# target to preprocess a source file
source/common/systems/forward-renderer.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/systems/forward-renderer.cpp.i
.PHONY : source/common/systems/forward-renderer.cpp.i

source/common/systems/forward-renderer.s: source/common/systems/forward-renderer.cpp.s

.PHONY : source/common/systems/forward-renderer.s

# target to generate assembly for a file
source/common/systems/forward-renderer.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/systems/forward-renderer.cpp.s
.PHONY : source/common/systems/forward-renderer.cpp.s

source/common/texture/sampler.o: source/common/texture/sampler.cpp.o

.PHONY : source/common/texture/sampler.o

# target to build an object file
source/common/texture/sampler.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/texture/sampler.cpp.o
.PHONY : source/common/texture/sampler.cpp.o

source/common/texture/sampler.i: source/common/texture/sampler.cpp.i

.PHONY : source/common/texture/sampler.i

# target to preprocess a source file
source/common/texture/sampler.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/texture/sampler.cpp.i
.PHONY : source/common/texture/sampler.cpp.i

source/common/texture/sampler.s: source/common/texture/sampler.cpp.s

.PHONY : source/common/texture/sampler.s

# target to generate assembly for a file
source/common/texture/sampler.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/texture/sampler.cpp.s
.PHONY : source/common/texture/sampler.cpp.s

source/common/texture/screenshot.o: source/common/texture/screenshot.cpp.o

.PHONY : source/common/texture/screenshot.o

# target to build an object file
source/common/texture/screenshot.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/texture/screenshot.cpp.o
.PHONY : source/common/texture/screenshot.cpp.o

source/common/texture/screenshot.i: source/common/texture/screenshot.cpp.i

.PHONY : source/common/texture/screenshot.i

# target to preprocess a source file
source/common/texture/screenshot.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/texture/screenshot.cpp.i
.PHONY : source/common/texture/screenshot.cpp.i

source/common/texture/screenshot.s: source/common/texture/screenshot.cpp.s

.PHONY : source/common/texture/screenshot.s

# target to generate assembly for a file
source/common/texture/screenshot.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/texture/screenshot.cpp.s
.PHONY : source/common/texture/screenshot.cpp.s

source/common/texture/texture-utils.o: source/common/texture/texture-utils.cpp.o

.PHONY : source/common/texture/texture-utils.o

# target to build an object file
source/common/texture/texture-utils.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/texture/texture-utils.cpp.o
.PHONY : source/common/texture/texture-utils.cpp.o

source/common/texture/texture-utils.i: source/common/texture/texture-utils.cpp.i

.PHONY : source/common/texture/texture-utils.i

# target to preprocess a source file
source/common/texture/texture-utils.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/texture/texture-utils.cpp.i
.PHONY : source/common/texture/texture-utils.cpp.i

source/common/texture/texture-utils.s: source/common/texture/texture-utils.cpp.s

.PHONY : source/common/texture/texture-utils.s

# target to generate assembly for a file
source/common/texture/texture-utils.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/common/texture/texture-utils.cpp.s
.PHONY : source/common/texture/texture-utils.cpp.s

source/main.o: source/main.cpp.o

.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i

.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s

.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

vendor/glad/src/gl.o: vendor/glad/src/gl.c.o

.PHONY : vendor/glad/src/gl.o

# target to build an object file
vendor/glad/src/gl.c.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/glad/src/gl.c.o
.PHONY : vendor/glad/src/gl.c.o

vendor/glad/src/gl.i: vendor/glad/src/gl.c.i

.PHONY : vendor/glad/src/gl.i

# target to preprocess a source file
vendor/glad/src/gl.c.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/glad/src/gl.c.i
.PHONY : vendor/glad/src/gl.c.i

vendor/glad/src/gl.s: vendor/glad/src/gl.c.s

.PHONY : vendor/glad/src/gl.s

# target to generate assembly for a file
vendor/glad/src/gl.c.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/glad/src/gl.c.s
.PHONY : vendor/glad/src/gl.c.s

vendor/imgui/imgui.o: vendor/imgui/imgui.cpp.o

.PHONY : vendor/imgui/imgui.o

# target to build an object file
vendor/imgui/imgui.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/imgui/imgui.cpp.o
.PHONY : vendor/imgui/imgui.cpp.o

vendor/imgui/imgui.i: vendor/imgui/imgui.cpp.i

.PHONY : vendor/imgui/imgui.i

# target to preprocess a source file
vendor/imgui/imgui.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/imgui/imgui.cpp.i
.PHONY : vendor/imgui/imgui.cpp.i

vendor/imgui/imgui.s: vendor/imgui/imgui.cpp.s

.PHONY : vendor/imgui/imgui.s

# target to generate assembly for a file
vendor/imgui/imgui.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/imgui/imgui.cpp.s
.PHONY : vendor/imgui/imgui.cpp.s

vendor/imgui/imgui_demo.o: vendor/imgui/imgui_demo.cpp.o

.PHONY : vendor/imgui/imgui_demo.o

# target to build an object file
vendor/imgui/imgui_demo.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/imgui/imgui_demo.cpp.o
.PHONY : vendor/imgui/imgui_demo.cpp.o

vendor/imgui/imgui_demo.i: vendor/imgui/imgui_demo.cpp.i

.PHONY : vendor/imgui/imgui_demo.i

# target to preprocess a source file
vendor/imgui/imgui_demo.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/imgui/imgui_demo.cpp.i
.PHONY : vendor/imgui/imgui_demo.cpp.i

vendor/imgui/imgui_demo.s: vendor/imgui/imgui_demo.cpp.s

.PHONY : vendor/imgui/imgui_demo.s

# target to generate assembly for a file
vendor/imgui/imgui_demo.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/imgui/imgui_demo.cpp.s
.PHONY : vendor/imgui/imgui_demo.cpp.s

vendor/imgui/imgui_draw.o: vendor/imgui/imgui_draw.cpp.o

.PHONY : vendor/imgui/imgui_draw.o

# target to build an object file
vendor/imgui/imgui_draw.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/imgui/imgui_draw.cpp.o
.PHONY : vendor/imgui/imgui_draw.cpp.o

vendor/imgui/imgui_draw.i: vendor/imgui/imgui_draw.cpp.i

.PHONY : vendor/imgui/imgui_draw.i

# target to preprocess a source file
vendor/imgui/imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/imgui/imgui_draw.cpp.i
.PHONY : vendor/imgui/imgui_draw.cpp.i

vendor/imgui/imgui_draw.s: vendor/imgui/imgui_draw.cpp.s

.PHONY : vendor/imgui/imgui_draw.s

# target to generate assembly for a file
vendor/imgui/imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/imgui/imgui_draw.cpp.s
.PHONY : vendor/imgui/imgui_draw.cpp.s

vendor/imgui/imgui_impl/imgui_impl_glfw.o: vendor/imgui/imgui_impl/imgui_impl_glfw.cpp.o

.PHONY : vendor/imgui/imgui_impl/imgui_impl_glfw.o

# target to build an object file
vendor/imgui/imgui_impl/imgui_impl_glfw.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/imgui/imgui_impl/imgui_impl_glfw.cpp.o
.PHONY : vendor/imgui/imgui_impl/imgui_impl_glfw.cpp.o

vendor/imgui/imgui_impl/imgui_impl_glfw.i: vendor/imgui/imgui_impl/imgui_impl_glfw.cpp.i

.PHONY : vendor/imgui/imgui_impl/imgui_impl_glfw.i

# target to preprocess a source file
vendor/imgui/imgui_impl/imgui_impl_glfw.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/imgui/imgui_impl/imgui_impl_glfw.cpp.i
.PHONY : vendor/imgui/imgui_impl/imgui_impl_glfw.cpp.i

vendor/imgui/imgui_impl/imgui_impl_glfw.s: vendor/imgui/imgui_impl/imgui_impl_glfw.cpp.s

.PHONY : vendor/imgui/imgui_impl/imgui_impl_glfw.s

# target to generate assembly for a file
vendor/imgui/imgui_impl/imgui_impl_glfw.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/imgui/imgui_impl/imgui_impl_glfw.cpp.s
.PHONY : vendor/imgui/imgui_impl/imgui_impl_glfw.cpp.s

vendor/imgui/imgui_impl/imgui_impl_opengl3.o: vendor/imgui/imgui_impl/imgui_impl_opengl3.cpp.o

.PHONY : vendor/imgui/imgui_impl/imgui_impl_opengl3.o

# target to build an object file
vendor/imgui/imgui_impl/imgui_impl_opengl3.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/imgui/imgui_impl/imgui_impl_opengl3.cpp.o
.PHONY : vendor/imgui/imgui_impl/imgui_impl_opengl3.cpp.o

vendor/imgui/imgui_impl/imgui_impl_opengl3.i: vendor/imgui/imgui_impl/imgui_impl_opengl3.cpp.i

.PHONY : vendor/imgui/imgui_impl/imgui_impl_opengl3.i

# target to preprocess a source file
vendor/imgui/imgui_impl/imgui_impl_opengl3.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/imgui/imgui_impl/imgui_impl_opengl3.cpp.i
.PHONY : vendor/imgui/imgui_impl/imgui_impl_opengl3.cpp.i

vendor/imgui/imgui_impl/imgui_impl_opengl3.s: vendor/imgui/imgui_impl/imgui_impl_opengl3.cpp.s

.PHONY : vendor/imgui/imgui_impl/imgui_impl_opengl3.s

# target to generate assembly for a file
vendor/imgui/imgui_impl/imgui_impl_opengl3.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/imgui/imgui_impl/imgui_impl_opengl3.cpp.s
.PHONY : vendor/imgui/imgui_impl/imgui_impl_opengl3.cpp.s

vendor/imgui/imgui_widgets.o: vendor/imgui/imgui_widgets.cpp.o

.PHONY : vendor/imgui/imgui_widgets.o

# target to build an object file
vendor/imgui/imgui_widgets.cpp.o:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/imgui/imgui_widgets.cpp.o
.PHONY : vendor/imgui/imgui_widgets.cpp.o

vendor/imgui/imgui_widgets.i: vendor/imgui/imgui_widgets.cpp.i

.PHONY : vendor/imgui/imgui_widgets.i

# target to preprocess a source file
vendor/imgui/imgui_widgets.cpp.i:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/imgui/imgui_widgets.cpp.i
.PHONY : vendor/imgui/imgui_widgets.cpp.i

vendor/imgui/imgui_widgets.s: vendor/imgui/imgui_widgets.cpp.s

.PHONY : vendor/imgui/imgui_widgets.s

# target to generate assembly for a file
vendor/imgui/imgui_widgets.cpp.s:
	$(MAKE) -f CMakeFiles/GAME_APPLICATION.dir/build.make CMakeFiles/GAME_APPLICATION.dir/vendor/imgui/imgui_widgets.cpp.s
.PHONY : vendor/imgui/imgui_widgets.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... GAME_APPLICATION"
	@echo "... glfw"
	@echo "... source/common/application.o"
	@echo "... source/common/application.i"
	@echo "... source/common/application.s"
	@echo "... source/common/asset-loader.o"
	@echo "... source/common/asset-loader.i"
	@echo "... source/common/asset-loader.s"
	@echo "... source/common/components/camera.o"
	@echo "... source/common/components/camera.i"
	@echo "... source/common/components/camera.s"
	@echo "... source/common/components/free-camera-controller.o"
	@echo "... source/common/components/free-camera-controller.i"
	@echo "... source/common/components/free-camera-controller.s"
	@echo "... source/common/components/mesh-renderer.o"
	@echo "... source/common/components/mesh-renderer.i"
	@echo "... source/common/components/mesh-renderer.s"
	@echo "... source/common/components/movement.o"
	@echo "... source/common/components/movement.i"
	@echo "... source/common/components/movement.s"
	@echo "... source/common/ecs/entity.o"
	@echo "... source/common/ecs/entity.i"
	@echo "... source/common/ecs/entity.s"
	@echo "... source/common/ecs/transform.o"
	@echo "... source/common/ecs/transform.i"
	@echo "... source/common/ecs/transform.s"
	@echo "... source/common/ecs/world.o"
	@echo "... source/common/ecs/world.i"
	@echo "... source/common/ecs/world.s"
	@echo "... source/common/material/material.o"
	@echo "... source/common/material/material.i"
	@echo "... source/common/material/material.s"
	@echo "... source/common/material/pipeline-state.o"
	@echo "... source/common/material/pipeline-state.i"
	@echo "... source/common/material/pipeline-state.s"
	@echo "... source/common/mesh/mesh-utils.o"
	@echo "... source/common/mesh/mesh-utils.i"
	@echo "... source/common/mesh/mesh-utils.s"
	@echo "... source/common/shader/shader.o"
	@echo "... source/common/shader/shader.i"
	@echo "... source/common/shader/shader.s"
	@echo "... source/common/systems/forward-renderer.o"
	@echo "... source/common/systems/forward-renderer.i"
	@echo "... source/common/systems/forward-renderer.s"
	@echo "... source/common/texture/sampler.o"
	@echo "... source/common/texture/sampler.i"
	@echo "... source/common/texture/sampler.s"
	@echo "... source/common/texture/screenshot.o"
	@echo "... source/common/texture/screenshot.i"
	@echo "... source/common/texture/screenshot.s"
	@echo "... source/common/texture/texture-utils.o"
	@echo "... source/common/texture/texture-utils.i"
	@echo "... source/common/texture/texture-utils.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... vendor/glad/src/gl.o"
	@echo "... vendor/glad/src/gl.i"
	@echo "... vendor/glad/src/gl.s"
	@echo "... vendor/imgui/imgui.o"
	@echo "... vendor/imgui/imgui.i"
	@echo "... vendor/imgui/imgui.s"
	@echo "... vendor/imgui/imgui_demo.o"
	@echo "... vendor/imgui/imgui_demo.i"
	@echo "... vendor/imgui/imgui_demo.s"
	@echo "... vendor/imgui/imgui_draw.o"
	@echo "... vendor/imgui/imgui_draw.i"
	@echo "... vendor/imgui/imgui_draw.s"
	@echo "... vendor/imgui/imgui_impl/imgui_impl_glfw.o"
	@echo "... vendor/imgui/imgui_impl/imgui_impl_glfw.i"
	@echo "... vendor/imgui/imgui_impl/imgui_impl_glfw.s"
	@echo "... vendor/imgui/imgui_impl/imgui_impl_opengl3.o"
	@echo "... vendor/imgui/imgui_impl/imgui_impl_opengl3.i"
	@echo "... vendor/imgui/imgui_impl/imgui_impl_opengl3.s"
	@echo "... vendor/imgui/imgui_widgets.o"
	@echo "... vendor/imgui/imgui_widgets.i"
	@echo "... vendor/imgui/imgui_widgets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

